---
- name: Notificar alerta
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Guardar todas las variables
      ansible.builtin.copy:
        content: "{{ vars | to_nice_json }}"
        dest: /tmp/vars.json