apiVersion: v1
kind: ConfigMap
metadata:
  name: eda-rulebook
data:
  rulebook.yml: |
    ---
    - name: Reaccionar a alertas
      hosts: all
      sources:
        - ansible.eda.alertmanager:
            host: 0.0.0.0
            port: 5000
      rules:
        - name: Alerta de prueba
          condition: event.alert.labels.alertname == "TestAlert"
          action:
            run_playbook:
              name: /rulebook/notify.yml
  notify.yml: |
{{ .Files.Get "files/notify.yml" | indent 4 }}