apiVersion: v1
kind: ConfigMap
metadata:
  name: eda-rulebook
data:
  rulebook.yml: |
    ---
    - name: Hola mundo
      hosts: all
      sources:
        - ansible.eda.range:
            limit: 5
      rules:
        - name: Decir algo
          condition: event.i == 1
          action:
            debug:
