apiVersion: v1
kind: ConfigMap
metadata:
  name: eda-rulebook
data:
  rulebook.yml: |
    ---
    - name: Reaccionar a alertas
      hosts: localhost
      sources:
        - ansible.eda.alertmanager:
            host: 0.0.0.0
            port: 5000
          filters:
            - eda.builtin.json_filter:
                exclude_keys:
                  - "meta.hosts"
      rules:
        - name: Alertas SRE
          condition: event.alert.labels.alertname is defined
          action:
            run_playbook:
              name: /rulebook/notify.yml
  inventory.yml: |
    all:
      hosts:
        localhost:
          ansible_connection: local
  notify.yml: |
{{ .Files.Get "files/notify.yml" | indent 4 }}