apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
  template:
    metadata:
      labels:
        app: eda
    spec:
      containers:
        - name: eda
          image: quay.io/ansible/ansible-rulebook:v1.3.2
          command:
            - ansible-rulebook
          args:
            - --rulebook
            - /rulebook/rulebook.yml
          ports:
            - containerPort: 5000
              name: webhook
          volumeMounts:
            - name: rulebook
              mountPath: /rulebook
      volumes:
        - name: rulebook
          configMap:
            name: eda-rulebook